apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csv-processor.fullname" . }}
  labels:
    {{- include "csv-processor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "csv-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- include "pod-annotations" . | nindent 6 }}
      labels:
        {{- include "csv-processor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "csv-processor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.flask }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.configmap.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "csv-processor.fullname" . }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.app.healthEndpoint }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.app.healthEndpoint }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: shared-volume
              mountPath: {{ .Values.volume.mountPath }}

      volumes:
        - name: shared-volume
          emptyDir: {}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
