apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csv-processor.fullname" . }}-nginx-config
data:
  default.conf: |-
    server {
      listen 80;

      location /static/ {
          alias /usr/share/nginx/html/static/;
          expires 30d;
          add_header Cache-Control "public";
      }

      location / {
          proxy_pass http://localhost:{{ .Values.service.targetPort }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
