{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "csv-processor.fullname" . }}
  labels:
    {{- include "csv-processor.labels" . | nindent 4 }}
type: Opaque    
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end -}}
