replicaCount: 2

image:
  flask: caglakahriman/flask-app:latest
  
service:
  type: ClusterIP
  targetPort: 5000
  port: 80
  protocol: TCP
  name: http

serviceAccount:
  create: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

config:
  FLASK_ENV: production

volume:
  mountPath: /shared
  claimName: shared-storage-pvc

secret:
  enabled: false
